### ISSUE TITLE
Add loading optional loading state

### ISSUE THREAD

**Issue by kentwalters** [tryretool/react-retool#11]
Provide the option for react-retool to show a loading indicator while the embedded Retool app is loading.

**Comment by FlorianRuen** [comment]
@kentwalters AS I can see this issue is closed, any reason ? I'm using this plugin, but I'm looking to use postMessage to send a message when the dashboard is loaded, because I can't find anything to display a loading state

**Comment by gvidaspr** [comment]
@FlorianRuen Heyy, did you find any solution to your problem?
