### ISSUE TITLE
Invalid hook call error for react-retool 1.0.2

### ISSUE THREAD

**Issue by lucash-0** [tryretool/react-retool#24]
Getting an invalid hook call when putting embedding the Retool component with version 1.0.2.

I downgraded to 0.4.1 and it started to work.

Here is the main error message from console logs:

`Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
`
[See all Chrome console logs.](https://github.com/tryretool/react-retool/files/8407227/3000.code.hahn.fun-1649053778759.log)

**Comment by kentwalters** [comment]
@lucash-0 fixed in [1.1.1](https://www.npmjs.com/package/react-retool)
