### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by nathan-stable-auto** [tryretool/react-retool#29]
Hello! I notice this repo lacks a LICENSE file, and as such it's unspecified if it's allowed to use within open-source projects. Would you be able to add a LICENSE file such as MIT, Apache, or BSD?

More context: https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license/1721#1721

Thank you!

**Comment by nathan-stable-auto** [comment]
cc @kentwalters

**Comment by kentwalters** [comment]
Great suggestion, thanks @nathan-stable-auto!
